name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: Matvind
        
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet someone'
        run: echo "Hello ${{ inputs.who-to-greet }}"
        
